# fly.toml app configuration file generated for starbot-6mhgrq on 2025-06-09T17:15:57Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'starbot-6mhgrq'
primary_region = 'fra'

[build]

# Настройки для предотвращения автоматического выключения
[deploy]
  strategy = "immediate"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  kill_signal = "SIGTERM"
  kill_timeout = "30s"
  restart_policy = "always"
